### ISSUE TITLE
2.0.0 changes

### ISSUE THREAD

**Issue by benschwarz** [calibreapp/cli#49]
Using this issue to track changes coming into CLI for 2.0.0 release. 

There's been a few things we've wanted to do but didn't because we didn't want to risk changing CLI flags etc. 

- [x] Add adblocking to single page tests. Add ability to turn it on or off for a test profile (#48)
- [x] Tidy up command line flags so that they're all `--dash-separated` rather than `--camelCase` (#48)
- [x] Rename flags used to turn JavaScript on / off (#48)
- [x] Remove GIF artifact download (#50)
- [x] Move `get-pulse-metrics` to use the top level `timeseries` query method
- [x] Add / Remove deploy markers (#52)
- [x] Change snapshots to use snapshotsList for pagination (#52)
- [x] Return completed, errored and timeout tests with runtimeError (#53)
- [x] Change the metrics chart for single page tests to swap out FMP for FCP (#54)
- [x] Match Lighthouse grade colours to app (#54)
